### PR TITLE
remove L from successfull in pom.xml file .

### PR DESCRIPTION
**Pull request by mrinal1209**
@martinda  please check the following issue resolved or not . https://issues.jenkins-ci.org/browse/JENKINS-53298

### CODE REVIEW

**Comment by martinda** [comment]
@mrinal1209 Look good to me.

**Comment by mrinal1209** [comment]
@ndeloof  can you please verify and merge my pull request as I am writing a GSOC proposal it would helpful if this request is merged ... THANK YOU.

**Comment by ndeloof** [comment]
I'm not maintaining this plugin anymore
see https://groups.google.com/d/msg/jenkinsci-dev/BLIfRisUyag/MX7lfaDKBAAJ

**Comment by martinda** [comment]
@mrinal1209 I have asked in the [mailing list](https://groups.google.com/forum/#!topic/jenkinsci-dev/886mRunmnTI) for advice on how to proceed

**Review by oleg-nenashev — APPROVED** [review]

**Comment by mrinal1209** [comment]
@oleg-nenashev  @martinda  can you please ask some one to merge this issue

**Pull request merged**
